// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressBalance.proto

public final class AddressBalance {
  private AddressBalance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressBalanceMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddressBalanceMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; address_balance = 1;</code>
     */
    int getAddressBalanceCount();
    /**
     * <code>map&lt;string, string&gt; address_balance = 1;</code>
     */
    boolean containsAddressBalance(
        java.lang.String key);
    /**
     * Use {@link #getAddressBalanceMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAddressBalance();
    /**
     * <code>map&lt;string, string&gt; address_balance = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAddressBalanceMap();
    /**
     * <code>map&lt;string, string&gt; address_balance = 1;</code>
     */

    java.lang.String getAddressBalanceOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; address_balance = 1;</code>
     */

    java.lang.String getAddressBalanceOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code AddressBalanceMap}
   */
  public  static final class AddressBalanceMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddressBalanceMap)
      AddressBalanceMapOrBuilder {
    // Use AddressBalanceMap.newBuilder() to construct.
    private AddressBalanceMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddressBalanceMap() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AddressBalanceMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                addressBalance_ = com.google.protobuf.MapField.newMapField(
                    AddressBalanceDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              addressBalance = input.readMessage(
                  AddressBalanceDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              addressBalance_.getMutableMap().put(addressBalance.getKey(), addressBalance.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AddressBalance.internal_static_AddressBalanceMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetAddressBalance();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AddressBalance.internal_static_AddressBalanceMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddressBalance.AddressBalanceMap.class, AddressBalance.AddressBalanceMap.Builder.class);
    }

    public static final int ADDRESS_BALANCE_FIELD_NUMBER = 1;
    private static final class AddressBalanceDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  AddressBalance.internal_static_AddressBalanceMap_AddressBalanceEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> addressBalance_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAddressBalance() {
      if (addressBalance_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AddressBalanceDefaultEntryHolder.defaultEntry);
      }
      return addressBalance_;
    }

    public int getAddressBalanceCount() {
      return internalGetAddressBalance().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; address_balance = 1;</code>
     */

    public boolean containsAddressBalance(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAddressBalance().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAddressBalanceMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAddressBalance() {
      return getAddressBalanceMap();
    }
    /**
     * <code>map&lt;string, string&gt; address_balance = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAddressBalanceMap() {
      return internalGetAddressBalance().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; address_balance = 1;</code>
     */

    public java.lang.String getAddressBalanceOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAddressBalance().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; address_balance = 1;</code>
     */

    public java.lang.String getAddressBalanceOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAddressBalance().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAddressBalance().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        addressBalance = AddressBalanceDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, addressBalance);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAddressBalance().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        addressBalance = AddressBalanceDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, addressBalance);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AddressBalance.AddressBalanceMap)) {
        return super.equals(obj);
      }
      AddressBalance.AddressBalanceMap other = (AddressBalance.AddressBalanceMap) obj;

      boolean result = true;
      result = result && internalGetAddressBalance().equals(
          other.internalGetAddressBalance());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetAddressBalance().getMap().isEmpty()) {
        hash = (37 * hash) + ADDRESS_BALANCE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAddressBalance().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AddressBalance.AddressBalanceMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressBalance.AddressBalanceMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressBalance.AddressBalanceMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressBalance.AddressBalanceMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressBalance.AddressBalanceMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddressBalance.AddressBalanceMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddressBalance.AddressBalanceMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AddressBalance.AddressBalanceMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddressBalance.AddressBalanceMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddressBalance.AddressBalanceMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AddressBalance.AddressBalanceMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddressBalanceMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddressBalanceMap)
        AddressBalance.AddressBalanceMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AddressBalance.internal_static_AddressBalanceMap_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetAddressBalance();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableAddressBalance();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AddressBalance.internal_static_AddressBalanceMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AddressBalance.AddressBalanceMap.class, AddressBalance.AddressBalanceMap.Builder.class);
      }

      // Construct using AddressBalance.AddressBalanceMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableAddressBalance().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AddressBalance.internal_static_AddressBalanceMap_descriptor;
      }

      public AddressBalance.AddressBalanceMap getDefaultInstanceForType() {
        return AddressBalance.AddressBalanceMap.getDefaultInstance();
      }

      public AddressBalance.AddressBalanceMap build() {
        AddressBalance.AddressBalanceMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AddressBalance.AddressBalanceMap buildPartial() {
        AddressBalance.AddressBalanceMap result = new AddressBalance.AddressBalanceMap(this);
        int from_bitField0_ = bitField0_;
        result.addressBalance_ = internalGetAddressBalance();
        result.addressBalance_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AddressBalance.AddressBalanceMap) {
          return mergeFrom((AddressBalance.AddressBalanceMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AddressBalance.AddressBalanceMap other) {
        if (other == AddressBalance.AddressBalanceMap.getDefaultInstance()) return this;
        internalGetMutableAddressBalance().mergeFrom(
            other.internalGetAddressBalance());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AddressBalance.AddressBalanceMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AddressBalance.AddressBalanceMap) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> addressBalance_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAddressBalance() {
        if (addressBalance_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AddressBalanceDefaultEntryHolder.defaultEntry);
        }
        return addressBalance_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAddressBalance() {
        onChanged();;
        if (addressBalance_ == null) {
          addressBalance_ = com.google.protobuf.MapField.newMapField(
              AddressBalanceDefaultEntryHolder.defaultEntry);
        }
        if (!addressBalance_.isMutable()) {
          addressBalance_ = addressBalance_.copy();
        }
        return addressBalance_;
      }

      public int getAddressBalanceCount() {
        return internalGetAddressBalance().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; address_balance = 1;</code>
       */

      public boolean containsAddressBalance(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAddressBalance().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAddressBalanceMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAddressBalance() {
        return getAddressBalanceMap();
      }
      /**
       * <code>map&lt;string, string&gt; address_balance = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAddressBalanceMap() {
        return internalGetAddressBalance().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; address_balance = 1;</code>
       */

      public java.lang.String getAddressBalanceOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAddressBalance().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; address_balance = 1;</code>
       */

      public java.lang.String getAddressBalanceOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAddressBalance().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAddressBalance() {
        getMutableAddressBalance().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; address_balance = 1;</code>
       */

      public Builder removeAddressBalance(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableAddressBalance().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAddressBalance() {
        return internalGetMutableAddressBalance().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; address_balance = 1;</code>
       */
      public Builder putAddressBalance(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableAddressBalance().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; address_balance = 1;</code>
       */

      public Builder putAllAddressBalance(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableAddressBalance().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AddressBalanceMap)
    }

    // @@protoc_insertion_point(class_scope:AddressBalanceMap)
    private static final AddressBalance.AddressBalanceMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AddressBalance.AddressBalanceMap();
    }

    public static AddressBalance.AddressBalanceMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddressBalanceMap>
        PARSER = new com.google.protobuf.AbstractParser<AddressBalanceMap>() {
      public AddressBalanceMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddressBalanceMap(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddressBalanceMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBalanceMap> getParserForType() {
      return PARSER;
    }

    public AddressBalance.AddressBalanceMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressBalanceMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddressBalanceMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressBalanceMap_AddressBalanceEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddressBalanceMap_AddressBalanceEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024addressBalance.proto\"\213\001\n\021AddressBalanc" +
      "eMap\022?\n\017address_balance\030\001 \003(\0132&.AddressB" +
      "alanceMap.AddressBalanceEntry\0325\n\023Address" +
      "BalanceEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001B\020B\016AddressBalanceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AddressBalanceMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddressBalanceMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddressBalanceMap_descriptor,
        new java.lang.String[] { "AddressBalance", });
    internal_static_AddressBalanceMap_AddressBalanceEntry_descriptor =
      internal_static_AddressBalanceMap_descriptor.getNestedTypes().get(0);
    internal_static_AddressBalanceMap_AddressBalanceEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddressBalanceMap_AddressBalanceEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
