/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kafka.volumeOut.stream

import kafka.volumeOut.stream.config.StreamConfig
import kafka.volumeOut.stream.serialization.BlockDeserializer
import kafka.volumeOut.stream.processor.VolumeOutProcessorSupplier
import org.apache.kafka.common.serialization.StringDeserializer
import org.apache.kafka.streams.*

fun main(args: Array<String>) {
    VolumeOutStream().start()
}

class VolumeOutStream(){
    fun start(){
        val balanceStream = KafkaStreams(getTopology(), StreamConfig.getStreamProperties())
        balanceStream.cleanUp()
        balanceStream.start()
        Runtime.getRuntime().addShutdownHook(Thread(balanceStream::close));
    }

    fun getTopology(): Topology{
        val topology = Topology()
        topology.addSource("Blockchain-producer", StringDeserializer(), BlockDeserializer(), "ethereum_blocks")
                .addProcessor("Processor", VolumeOutProcessorSupplier(), "Blockchain-producer")
                .addStateStore(StreamConfig.getAddressBalanceStoreSupplier(), "Processor")
                .addSink("Balance-stream", "balance", "Processor")

        return topology
    }

}